version: '3'
services:
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - appNetwork

  api:
    build: ./api
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
    ports:
      - 5000:5000
    networks:
      - appNetwork

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - appNetwork

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SistemaPostulacion
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - appNetwork

networks:
  appNetwork:
